name: Feature request
description: Sugiere una idea para este proyecto
title: "[FEATURE]: "
labels: ["enhancement"]
projects: ["UXCorpRangel/1"]
body:
  - type: markdown
    attributes:
      value: |
        **¿Tu solicitud está relacionada con un problema? Por favor, descríbelo.**
  - type: checkboxes
    id: cat-preferences
    attributes:
      label: What kinds of cats do you like?
      description: You may select more than one.
      options:
        - label: Orange cat (required. Everyone likes orange cats.)
          required: true
        - label: **Black cat**
